name: Build and deploy Node.js app to Azure Web App - news-classification

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies, build and test Next.js (frontend)
        working-directory: ./mlops-fp  # Specify the folder for frontend
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip frontend artifact for deployment
        working-directory: ./mlops-fp  # Zip the frontend output
        run: zip -r ../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_21432C34E1034A48BB7E0C9D9D904D68 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_15C3CCACE91D4B54933835F0826E232A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_596C6FC328A1472E9815D1EECEFC481D }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'news-classification'
          slot-name: 'Production'
          package: .
