name: Build, Test, and Deploy Python app to Azure Web App - news-backend-pso
on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create Waitress startup command
        run: |
          echo "waitress-serve --port=8000 app:app" > startup.txt

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip app.py models requirements.txt startup.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

      - name: Cleanup - Deactivate and remove virtual environment
        run: |
          deactivate
          rm -rf venv

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install pytest
        run: |
          pip install pytest

      - name: Run tests with pytest
        run: |
          pytest test_app.py --maxfail=1 --disable-warnings -q

      - name: Cleanup - Deactivate and remove virtual environment
        run: |
          deactivate
          rm -rf venv

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]  # Ensure deployment only happens after tests pass
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  #This is required for requesting the JWT
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Verify downloaded artifact
        run: ls

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4AA54ACA24144C6E9C43F49EF18BF649 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C4FAE98C51F344C485B2F7C78AF3C8DA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F32A9B46E2674F89A17C52C2380E5A8F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'news-backend-pso'
          slot-name: 'Production'
          package: './release.zip'
