# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
name: Build and deploy Python app to Azure Web App - news-classification-backend
on:
  push:
    branches:
      - production
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Create Gunicorn startup command
        run: |
          echo "gunicorn --bind=0.0.0.0 --timeout 600 app:app" > startup.txt

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip app.py backend backend/requirements.txt startup.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Verify downloaded artifact
        run: ls

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EF22F7DD04C14055834D741579AFD163 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_48F858A8294047B8BE4AE98602830906 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9DADFE10865E47DCA17F720FBA6AA4A8 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'news-classification-backend'
          slot-name: 'Production'
          package: './release.zip'
